In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
sold_tickets = pd.read_csv('../data/london_ticket_sales.csv')
all_tickets = pd.read_csv('../data/london_tickets_for_sale.csv', encoding='latin1')
infra = pd.read_csv('../data/london_infrastructure_spending.csv', encoding='latin1')

In [105]:
sold_tickets.head(10)

  session    price  number_sold  total_public_sold  percent_sold_to_public
0   AT001      150        16704            46425.0               73.155166
1   AT001       95         7193            46425.0               73.155166
2   AT001       65         6721            46425.0               73.155166
3   AT001       40         4434            46425.0               73.155166
4   AT001       20         5336            46425.0               73.155166
5   AT001  Special         6037            46425.0               73.155166
6   AT002      450         5750            45969.0               72.978251
7   AT002      295        12317            45969.0               72.978251
8   AT002      150         8572            45969.0               72.978251
9   AT002       95         9199            45969.0               72.978251

In [70]:
sold_tickets['session'].nunique()

189

In [72]:
sold_tickets['percent_sold_to_public'].nunique()

188

In [67]:
sold_tickets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 938 entries, 0 to 937
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   session                 938 non-null    object
 1   price                   938 non-null    object
 2   number_sold             938 non-null    int64
 3   total_public_sold       868 non-null    float64
 4   percent_sold_to_public  938 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 36.8+ KB

In [106]:
all_tickets.head(10)

,date,time,gender,session,medal_ceremony,code,AA,A,B,C,D,E,limit,venue,event
0,03-Aug,10:0013:45,M,400m Hurdles: round 1,NaN,AT001,,150,95,65,40,20,20.0,Olympic Park - Olympic Stadium,Athletics
1,03-Aug,10:0013:45,M,3000m Steeplechase: round 1,NaN,AT001,,150,95,65,40,20,20.0,Olympic Park - Olympic Stadium,Athletics
2,03-Aug,10:0013:45,M,Hammer: qualifying,NaN,AT001,,150,95,65,40,20,20.0,Olympic Park - Olympic Stadium,Athletics
3,03-Aug,10:0013:45,M,Shot Put: qualifying,NaN,AT001,,150,95,65,40,20,20.0,Olympic Park - Olympic Stadium,Athletics
4,03-Aug,10:0013:45,W,100m: classification heats,NaN,AT001,,150,95,65,40,20,20.0,Olympic Park - Olympic Stadium,Athletics
5,03-Aug,10:0013:45,W,400m: round 1,NaN,AT001,,150,95,65,40,20,20.0,Olympic Park - Olympic Stadium,Athletics
6,03-Aug,10:0013:45,W,Triple Jump: qualifying,NaN,AT001,,150,95,65,40,20,20.0,Olympic Park - Olympic Stadium,Athletics
7,03-Aug,10:0013:45,W,Heptathlon: 100m hurdles; high jump,NaN,AT001,,150,95,65,40,20,20.0,Olympic Park - Olympic Stadium,Athletics
8,03-Aug,19:0021:55,M,1500m: round 1,NaN,AT002,,450,295,150,95,50,6.0,Olympic Park - Olympic Stadium,Athletics
9,03-Aug,19:0021:55,M,Long Jump: qualifying,NaN,AT002,,450,295,150,95,50,6.0,Olympic Park - Olympic Stadium,Athletics

In [11]:
infra.head()

,expense_category,breakdown,baseline_budget,31/12/2011_forecast,31/03/2012_forecast,variance
0,Site Preparation and Infrastructure,Powerlines,282.0,286,287,1.0
1,Site Preparation and Infrastructure,Utilities,256.0,238,235,-3.0
2,Site Preparation and Infrastructure,Enabling Works,364.0,386,386,0.0
3,Site Preparation and Infrastructure,F10 Bridge,89.0,56,55,-1.0
4,Site Preparation and Infrastructure,"Other Structures, Bridges and Highways",740.0,553,565,12.0

In [12]:
session_codes = set(all_tickets['code'])

In [36]:
venues = sorted(list(set(all_tickets['venue'])))

In [37]:
venue_spendings = infra.loc[infra['expense_category'] == 'Venues']

# from all venues, how much it cost (last estimate)
venue_to_cost = {} 
for (i,r) in venue_spendings.iterrows(): 
    venue = r.at['breakdown']
    cost = r.at['31/03/2012_forecast']
    venue_to_cost[venue] = cost # in millions of pounds 
venue_to_cost

{'Stadium': 428,
 'Aquatics': 251,
 'Velopark': 87,
 'Handball': 41,
 'Basketball': 40,
 'Other Olympic Park Venues': 101,
 'Non-Olympic Park Venues': 103,
 'Total Venues': 1051}

In [38]:
# from all tickets, we need the session codes associated with a venue 
venue_to_sessions = {} 
for v in venues: 
    venue_sessions = all_tickets.loc[ all_tickets['venue'] == v ]
    venue_sessions_code = set(venue_sessions['code'])
    
    venue_to_sessions[v] = venue_sessions_code
venue_to_sessions

{'City of Coventry Stadium; Coventry': {'FB002',
  'FB004',
  'FB009',
  'FB013',
  'FB018',
  'FB023',
  'FB027',
  'FB039'},
 'Earls Court': {'VO001',
  'VO002',
  'VO003',
  'VO004',
  'VO005',
  'VO006',
  'VO007',
  'VO008',
  'VO009',
  'VO010',
  'VO011',
  'VO012',
  'VO013',
  'VO014',
  'VO015',
  'VO016',
  'VO017',
  'VO018',
  'VO019',
  'VO020',
  'VO021',
  'VO022',
  'VO023',
  'VO024',
  'VO025',
  'VO026',
  'VO027',
  'VO028',
  'VO029',
  'VO030',
  'VO031',
  'VO032',
  'VO033',
  'VO034',
  'VO035',
  'VO036',
  'VO037',
  'VO038',
  'VO039',
  'VO040',
  'VO041',
  'VO042'},
 'Eton Dorney; Buckinghamshire': {'CF001',
  'CF002',
  'CF003',
  'CF004',
  'CF005',
  'CF006',
  'RO001',
  'RO002',
  'RO003',
  'RO004',
  'RO005',
  'RO006',
  'RO007',
  'RO008'},
 'ExCeL': {'BX001',
  'BX002',
  'BX003',
  'BX004',
  'BX005',
  'BX006',
  'BX007',
  'BX008',
  'BX009',
  'BX010',
  'BX011',
  'BX012',
  'BX013',
  'BX014',
  'BX015',
  'BX016',
  'BX017',
  'BX018',
  'BX019',
  'BX020',
  'BX021',
  'BX022',
  'BX023',
  'BX024',
  'BX025',
  'BX026',
  'BX027',
  'BX028',
  'FE001',
  'FE002',
  'FE003',
  'FE004',
  'FE005',
  'FE006',
  'FE007',
  'FE008',
  'FE009',
  'FE010',
  'FE011',
  'FE012',
  'FE013',
  'FE014',
  'FE015',
  'FE016',
  'FE017',
  'FE018',
  'JU001',
  'JU002',
  'JU003',
  'JU004',
  'JU005',
  'JU006',
  'JU007',
  'JU008',
  'JU009',
  'JU010',
  'JU011',
  'JU012',
  'JU013',
  'JU014',
  'TK001',
  'TK002',
  'TK003',
  'TK004',
  'TK005',
  'TK006',
  'TK007',
  'TK008',
  'TK009',
  'TK010',
  'TK011',
  'TK012',
  'TT001',
  'TT002',
  'TT003',
  'TT004',
  'TT005',
  'TT006',
  'TT007',
  'TT008',
  'TT009',
  'TT010',
  'TT011',
  'TT012',
  'TT013',
  'TT014',
  'TT015',
  'TT016',
  'TT017',
  'TT018',
  'TT019',
  'TT020',
  'TT021',
  'TT022',
  'TT023',
  'TT024',
  'TT025',
  'TT026',
  'TT027',
  'TT028',
  'TT029',
  'TT030',
  'TT031',
  'TT032',
  'WF001',
  'WF002',
  'WF003',
  'WF004',
  'WF005',
  'WF006',
  'WF007',
  'WF008',
  'WF009',
  'WF010',
  'WG001',
  'WG002',
  'WG003',
  'WG004',
  'WG005',
  'WG006',
  'WL001',
  'WL002',
  'WL003',
  'WL004',
  'WL005',
  'WL006',
  'WL007',
  'WL008',
  'WL009',
  'WL010',
  'WL011',
  'WL012',
  'WL013',
  'WL014',
  'WL015',
  'WL016',
  'WL017',
  'WL018',
  'WL019',
  'WL020',
  'WL021',
  'WL022',
  'WL023'},
 'Greenwich Park': {'ED001',
  'ED002',
  'ED003',
  'ED004',
  'EJ001',
  'EJ002',
  'EJ003',
  'EJ004',
  'EV001',
  'EV002',
  'EV003',
  'EV004'},
 'Hadleigh Farm; Essex': {'CM001', 'CM002'},
 'Hampden Park; Glasgow': {'FB003', 'FB005', 'FB011', 'FB021', 'FB030'},
 'Horse Guards Parade': {'BV001',
  'BV002',
  'BV003',
  'BV004',
  'BV005',
  'BV006',
  'BV007',
  'BV008',
  'BV009',
  'BV010',
  'BV011',
  'BV012',
  'BV013',
  'BV014',
  'BV015',
  'BV016',
  'BV017',
  'BV018',
  'BV019',
  'BV020',
  'BV021',
  'BV022',
  'BV023',
  'BV024',
  'BV025',
  'BV026',
  'BV027',
  'BV028',
  'BV029',
  'BV030',
  'BV031',
  'BV032',
  'BV033',
  'BV034'},
 'Hyde Park': {'SM001', 'SM002', 'TR001', 'TR002'},
 'Lee Valley White Water Centre; Hertfordshire': {'CS001',
  'CS002',
  'CS003',
  'CS004',
  'CS005'},
 "Lord's Cricket Ground": {'AR003',
  'AR004',
  'AR005',
  'AR006',
  'AR007',
  'AR008',
  'AR009',
  'AR010',
  'AR011',
  'AR012',
  'AR013',
  'AR014',
  'AR015',
  'AR016',
  '\x96'},
 'Millennium Stadium; Cardiff': {'FB001',
  'FB008',
  'FB010',
  'FB019',
  'FB024',
  'FB029',
  'FB033',
  'FB041'},
 'North Greenwich Arena': {'BK033',
  'BK034',
  'BK035',
  'BK036',
  'BK037',
  'BK038',
  'BK039',
  'BK040',
  'BK041',
  'BK042',
  'GA001',
  'GA002',
  'GA003',
  'GA004',
  'GA005',
  'GA006',
  'GA007',
  'GA008',
  'GA009',
  'GA010',
  'GA011',
  'GA012',
  'GA013',
  'GT001',
  'GT002'},
 'Old Trafford; Manchester': {'FB007',
  'FB012',
  'FB017',
  'FB025',
  'FB031',
  'FB035',
  'FB037'},
 'Olympic Park - BMX Circuit': {'CB001', 'CB002', 'CB003'},
 'Olympic Park - Basketball Arena': {'BK001',
  'BK002',
  'BK003',
  'BK004',
  'BK005',
  'BK006',
  'BK007',
  'BK008',
  'BK009',
  'BK010',
  'BK011',
  'BK012',
  'BK013',
  'BK014',
  'BK015',
  'BK016',
  'BK017',
  'BK018',
  'BK019',
  'BK020',
  'BK021',
  'BK022',
  'BK023',
  'BK024',
  'BK025',
  'BK026',
  'BK027',
  'BK028',
  'BK029',
  'BK030',
  'BK031',
  'BK032',
  'HB035',
  'HB036',
  'HB037',
  'HB038',
  'HB039',
  'HB040',
  'HB041',
  'HB042',
  'HB043',
  'HB044',
  'HB045',
  'HB046'},
 'Olympic Park - Handball Arena': {'HB001',
  'HB002',
  'HB003',
  'HB004',
  'HB005',
  'HB006',
  'HB007',
  'HB008',
  'HB009',
  'HB010',
  'HB011',
  'HB012',
  'HB013',
  'HB014',
  'HB015',
  'HB016',
  'HB017',
  'HB018',
  'HB019',
  'HB020',
  'HB021',
  'HB022',
  'HB023',
  'HB024',
  'HB025',
  'HB026',
  'HB027',
  'HB028',
  'HB029',
  'HB030',
  'HB031',
  'HB032',
  'HB033',
  'HB034'},
 'Olympic Park - Olympic Stadium': {'AT001',
  'AT002',
  'AT003',
  'AT004',
  'AT005',
  'AT006',
  'AT007',
  'AT008',
  'AT009',
  'AT010',
  'AT011',
  'AT012',
  'AT013',
  'AT014',
  'AT015'},
 'Olympic Park \x96 Aquatics Centre': {'DV001',
  'DV002',
  'DV003',
  'DV004',
  'DV005',
  'DV006',
  'DV007',
  'DV008',
  'DV009',
  'DV010',
  'DV011',
  'DV012',
  'DV013',
  'DV014',
  'DV015',
  'DV016',
  'SW001',
  'SW002',
  'SW003',
  'SW004',
  'SW005',
  'SW006',
  'SW007',
  'SW008',
  'SW009',
  'SW010',
  'SW011',
  'SW012',
  'SW013',
  'SW014',
  'SW015',
  'SY001',
  'SY002',
  'SY003',
  'SY004',
  'SY005'},
 'Olympic Park \x96 Handball Arena: Fencing; Olympic Park \x96 Aquatics Centre: Swimming; Greenwich Park: Riding; combined event': {'MP001',
  'MP002',
  'MP003',
  'MP004'},
 'Olympic Park \x96 Hockey Centre': {'HO001',
  'HO002',
  'HO003',
  'HO004',
  'HO005',
  'HO006',
  'HO007',
  'HO008',
  'HO009',
  'HO010',
  'HO011',
  'HO012',
  'HO013',
  'HO014',
  'HO015',
  'HO016',
  'HO017',
  'HO018',
  'HO019',
  'HO020',
  'HO021',
  'HO022',
  'HO023',
  'HO024',
  'HO025',
  'HO026',
  'HO027',
  'HO028',
  'HO029',
  'HO030',
  'HO031',
  'HO032',
  'HO033',
  'HO034',
  'HO035',
  'HO036',
  'HO037',
  'HO038',
  'HO039',
  'HO040',
  'HO041',
  'HO042'},
 'Olympic Park \x96 Velodrome': {'CT001',
  'CT002',
  'CT003',
  'CT004',
  'CT005',
  'CT006',
  'CT007',
  'CT008',
  'CT009'},
 'Olympic Park \x96 Water Polo Arena': {'WP001',
  'WP002',
  'WP003',
  'WP004',
  'WP005',
  'WP006',
  'WP007',
  'WP008',
  'WP009',
  'WP010',
  'WP011',
  'WP012',
  'WP013',
  'WP014',
  'WP015',
  'WP016',
  'WP017',
  'WP018',
  'WP019',
  'WP020',
  'WP021',
  'WP022',
  'WP023',
  'WP024',
  'WP025',
  'WP026',
  'WP027',
  'WP028',
  'WP029',
  'WP030',
  'WP031',
  'WP032',
  'WP033'},
 'Royal Artillery Barracks - Finals Hall & Ground Pass': {'SH001',
  'SH002',
  'SH004',
  'SH007',
  'SH009',
  'SH010',
  'SH012',
  'SH014'},
 'Royal Artillery Barracks - Ground Pass': {'SH003',
  'SH005',
  'SH006',
  'SH008',
  'SH011',
  'SH013',
  'SH015'},
 'St James\x92 Park; Newcastle': {'FB006',
  'FB014',
  'FB016',
  'FB022',
  'FB028',
  'FB034'},
 'The Mall': {'AM001',
  'AM002',
  'AW001',
  'AW002',
  'AW003',
  'CR001',
  'CR002',
  '\x96'},
 'Wembley Arena': {'BD001',
  'BD002',
  'BD003',
  'BD004',
  'BD005',
  'BD006',
  'BD007',
  'BD008',
  'BD009',
  'BD010',
  'BD011',
  'BD012',
  'BD013',
  'BD014',
  'BD015',
  'BD016',
  'BD017',
  'BD018',
  'BD019',
  'BD020',
  'BD021',
  'BD022',
  'BD023',
  'BD024',
  'GR001',
  'GR002',
  'GR003',
  'GR004'},
 'Wembley Stadium': {'FB015',
  'FB020',
  'FB026',
  'FB032',
  'FB036',
  'FB038',
  'FB040',
  'FB042'},
 'Weymouth and Portland; Dorset': {'SA001',
  'SA002',
  'SA003',
  'SA004',
  'SA005',
  'SA006',
  'SA007',
  'SA008',
  'SA009',
  'SA010',
  'SA011',
  'SA012',
  'SA013',
  'SA014'},
 'Wimbledon - Centre Court': {'TE001',
  'TE004',
  'TE007',
  'TE010',
  'TE013',
  'TE016',
  'TE019',
  'TE021',
  'TE023'},
 'Wimbledon - Ground Pass': {'TE003',
  'TE006',
  'TE009',
  'TE012',
  'TE015',
  'TE018'},
 'Wimbledon - No.1 Court': {'TE002',
  'TE005',
  'TE008',
  'TE011',
  'TE014',
  'TE017',
  'TE020',
  'TE022',
  'TE024'}}

In [39]:
# for each venue we need the category it falls in 
categories = list(venue_to_cost.keys() )
list(categories) # 8 categories

['Stadium',
 'Aquatics',
 'Velopark',
 'Handball',
 'Basketball',
 'Other Olympic Park Venues',
 'Non-Olympic Park Venues',
 'Total Venues']

In [35]:
venues_df = pd.DataFrame(venues)
venues_df.head()

                                                    0
0                        Eton Dorney; Buckinghamshire
1                            Olympic Park  Velodrome
2                               Hampden Park; Glasgow
3                              Wimbledon - No.1 Court
4                                           Hyde Park
5                     Olympic Park  Water Polo Arena
6        Lee Valley White Water Centre; Hertfordshire
7                      Olympic Park - Olympic Stadium
8                             Wimbledon - Ground Pass
9                                       Wembley Arena
10                    Olympic Park - Basketball Arena
11             Royal Artillery Barracks - Ground Pass
12                      Olympic Park - Handball Arena
13                      Weymouth and Portland; Dorset
14                           Wimbledon - Centre Court
15                                        Earls Court
16                        Millennium Stadium; Cardiff
17                                Horse Guards Parade
18                               Hadleigh Farm; Essex
19                                     Greenwich Park
20                                              ExCeL
21                              Lord's Cricket Ground
22                 City of Coventry Stadium; Coventry
23                     Olympic Park  Aquatics Centre
24  Royal Artillery Barracks - Finals Hall & Groun...
25                                    Wembley Stadium
26                          St James Park; Newcastle
27  Olympic Park  Handball Arena: Fencing; Olympi...
28                         Olympic Park - BMX Circuit
29                              North Greenwich Arena
30                       Olympic Park  Hockey Centre
31                           Old Trafford; Manchester
32                                           The Mall

In [55]:
# manually match the venues from tickets to venues from spending 
in_OP = [7,5,23,1,28,12,10,27,30]
not_in_London = [0,2,6,13,16,18,22,26,31]
not_in_OP = set(range(0,33)).difference(set(in_OP)).difference(set(not_in_London)) 

london_venues_dict = {
    categories[0] : [venues_df.iloc[7].values[0]],
    categories[1] : [venues_df.iloc[5].values[0], venues_df.iloc[23].values[0] ],
    categories[2] : [venues_df.iloc[1].values[0], venues_df.iloc[28].values[0] ],
    categories[3] : [venues_df.iloc[12].values[0]],
    categories[4] : [venues_df.iloc[10].values[0]],
    categories[5] : [venues_df.iloc[27].values[0], venues_df.iloc[30].values[0]],
    
    categories[6] : [venues_df.iloc[i].values[0] for i in not_in_OP]
}

london_venues_dict

{'Stadium': ['Olympic Park - Olympic Stadium'],
 'Aquatics': ['Olympic Park \x96 Water Polo Arena',
  'Olympic Park \x96 Aquatics Centre'],
 'Velopark': ['Olympic Park \x96 Velodrome', 'Olympic Park - BMX Circuit'],
 'Handball': ['Olympic Park - Handball Arena'],
 'Basketball': ['Olympic Park - Basketball Arena'],
 'Other Olympic Park Venues': ['Olympic Park \x96 Handball Arena: Fencing; Olympic Park \x96 Aquatics Centre: Swimming; Greenwich Park: Riding; combined event',
  'Olympic Park \x96 Hockey Centre'],
 'Non-Olympic Park Venues': ['The Mall',
  'Wimbledon - No.1 Court',
  'Hyde Park',
  'Wimbledon - Ground Pass',
  'Wembley Arena',
  'Royal Artillery Barracks - Ground Pass',
  'Wimbledon - Centre Court',
  'Earls Court',
  'Horse Guards Parade',
  'Greenwich Park',
  'ExCeL',
  "Lord's Cricket Ground",
  'Royal Artillery Barracks - Finals Hall & Ground Pass',
  'Wembley Stadium',
  'North Greenwich Arena']}

In [112]:
# venue category to session 
category_to_sessions = {}

for c in categories: 
    if c == 'Total Venues':
        continue
    c_venues = london_venues_dict[c]
    c_sessions = []
    for v in c_venues: 
        sessions = venue_to_sessions[v]
        c_sessions = c_sessions + list(sessions)
      
    category_to_sessions[c] = c_sessions
category_to_sessions

{'Stadium': ['AT008',
  'AT011',
  'AT014',
  'AT010',
  'AT002',
  'AT009',
  'AT013',
  'AT001',
  'AT004',
  'AT006',
  'AT012',
  'AT003',
  'AT015',
  'AT005',
  'AT007'],
 'Aquatics': ['WP030',
  'WP015',
  'WP029',
  'WP026',
  'WP020',
  'WP006',
  'WP010',
  'WP018',
  'WP028',
  'WP022',
  'WP023',
  'WP027',
  'WP009',
  'WP033',
  'WP007',
  'WP005',
  'WP011',
  'WP016',
  'WP031',
  'WP017',
  'WP008',
  'WP013',
  'WP002',
  'WP001',
  'WP019',
  'WP024',
  'WP014',
  'WP025',
  'WP021',
  'WP032',
  'WP012',
  'WP004',
  'WP003',
  'DV014',
  'SW006',
  'SY001',
  'SW011',
  'DV003',
  'SW007',
  'DV013',
  'SW009',
  'SW010',
  'SW014',
  'DV016',
  'SY004',
  'SW003',
  'DV001',
  'DV011',
  'SW005',
  'SW013',
  'SW015',
  'DV010',
  'DV004',
  'SY003',
  'DV002',
  'DV015',
  'SY002',
  'DV005',
  'SW008',
  'SW002',
  'DV007',
  'DV008',
  'SW004',
  'SW001',
  'DV009',
  'DV012',
  'SY005',
  'DV006',
  'SW012'],
 'Velopark': ['CT006',
  'CT009',
  'CT004',
  'CT002',
  'CT008',
  'CT001',
  'CT003',
  'CT007',
  'CT005',
  'CB002',
  'CB003',
  'CB001'],
 'Handball': ['HB001',
  'HB018',
  'HB019',
  'HB006',
  'HB002',
  'HB027',
  'HB024',
  'HB026',
  'HB013',
  'HB005',
  'HB033',
  'HB012',
  'HB034',
  'HB028',
  'HB025',
  'HB010',
  'HB008',
  'HB004',
  'HB003',
  'HB009',
  'HB020',
  'HB015',
  'HB021',
  'HB032',
  'HB011',
  'HB022',
  'HB023',
  'HB029',
  'HB030',
  'HB017',
  'HB016',
  'HB007',
  'HB014',
  'HB031'],
 'Basketball': ['HB045',
  'BK015',
  'HB042',
  'BK004',
  'HB043',
  'BK026',
  'BK013',
  'HB035',
  'HB036',
  'BK006',
  'HB046',
  'BK024',
  'BK010',
  'BK022',
  'HB039',
  'BK008',
  'BK029',
  'BK028',
  'BK011',
  'BK014',
  'BK027',
  'BK030',
  'BK019',
  'BK032',
  'HB040',
  'BK009',
  'HB037',
  'BK016',
  'BK002',
  'HB038',
  'BK020',
  'BK025',
  'BK005',
  'BK018',
  'BK012',
  'BK017',
  'BK007',
  'BK001',
  'HB041',
  'BK031',
  'BK003',
  'BK023',
  'HB044',
  'BK021'],
 'Other Olympic Park Venues': ['MP004',
  'MP003',
  'MP002',
  'MP001',
  'HO010',
  'HO034',
  'HO002',
  'HO011',
  'HO026',
  'HO030',
  'HO028',
  'HO006',
  'HO041',
  'HO022',
  'HO021',
  'HO004',
  'HO018',
  'HO008',
  'HO032',
  'HO025',
  'HO039',
  'HO023',
  'HO042',
  'HO036',
  'HO024',
  'HO017',
  'HO033',
  'HO009',
  'HO027',
  'HO031',
  'HO035',
  'HO019',
  'HO037',
  'HO038',
  'HO040',
  'HO007',
  'HO029',
  'HO013',
  'HO016',
  'HO014',
  'HO003',
  'HO001',
  'HO012',
  'HO005',
  'HO015',
  'HO020'],
 'Non-Olympic Park Venues': ['AW002',
  'AW003',
  '\x96',
  'AM002',
  'CR001',
  'CR002',
  'AW001',
  'AM001',
  'TE014',
  'TE008',
  'TE002',
  'TE005',
  'TE024',
  'TE020',
  'TE022',
  'TE017',
  'TE011',
  'SM001',
  'TR001',
  'SM002',
  'TR002',
  'TE015',
  'TE018',
  'TE012',
  'TE009',
  'TE003',
  'TE006',
  'BD005',
  'BD022',
  'BD020',
  'GR001',
  'BD010',
  'BD013',
  'BD009',
  'BD024',
  'BD007',
  'BD016',
  'BD006',
  'BD001',
  'BD008',
  'BD021',
  'BD003',
  'BD023',
  'BD014',
  'GR004',
  'BD011',
  'GR003',
  'GR002',
  'BD017',
  'BD019',
  'BD015',
  'BD018',
  'BD004',
  'BD002',
  'BD012',
  'SH005',
  'SH003',
  'SH011',
  'SH013',
  'SH006',
  'SH015',
  'SH008',
  'TE019',
  'TE016',
  'TE023',
  'TE001',
  'TE021',
  'TE010',
  'TE013',
  'TE007',
  'TE004',
  'VO023',
  'VO015',
  'VO014',
  'VO020',
  'VO025',
  'VO001',
  'VO003',
  'VO017',
  'VO029',
  'VO030',
  'VO028',
  'VO002',
  'VO034',
  'VO037',
  'VO008',
  'VO004',
  'VO024',
  'VO007',
  'VO016',
  'VO033',
  'VO032',
  'VO011',
  'VO005',
  'VO019',
  'VO031',
  'VO040',
  'VO026',
  'VO018',
  'VO022',
  'VO009',
  'VO013',
  'VO042',
  'VO012',
  'VO035',
  'VO006',
  'VO027',
  'VO036',
  'VO039',
  'VO038',
  'VO041',
  'VO010',
  'VO021',
  'BV004',
  'BV005',
  'BV016',
  'BV033',
  'BV021',
  'BV010',
  'BV001',
  'BV027',
  'BV024',
  'BV006',
  'BV025',
  'BV018',
  'BV009',
  'BV034',
  'BV015',
  'BV013',
  'BV012',
  'BV007',
  'BV019',
  'BV029',
  'BV002',
  'BV032',
  'BV031',
  'BV023',
  'BV030',
  'BV020',
  'BV011',
  'BV008',
  'BV014',
  'BV026',
  'BV017',
  'BV028',
  'BV022',
  'BV003',
  'EV003',
  'EJ001',
  'EV002',
  'EJ004',
  'ED002',
  'ED003',
  'ED001',
  'ED004',
  'EV004',
  'EJ003',
  'EV001',
  'EJ002',
  'FE018',
  'WL020',
  'FE009',
  'TT001',
  'BX021',
  'TT010',
  'BX012',
  'TT016',
  'WL016',
  'FE008',
  'TK007',
  'TK006',
  'WL014',
  'WL015',
  'WL004',
  'JU001',
  'TT025',
  'BX019',
  'TT015',
  'WG003',
  'TT030',
  'BX004',
  'WF009',
  'JU008',
  'JU004',
  'FE004',
  'WL019',
  'WL022',
  'WF003',
  'JU010',
  'WF008',
  'WG002',
  'TK001',
  'TT029',
  'BX005',
  'TK010',
  'TK004',
  'TT005',
  'TT014',
  'BX001',
  'TT021',
  'WL009',
  'WL001',
  'BX023',
  'FE013',
  'TT004',
  'WL013',
  'FE010',
  'WG004',
  'WL010',
  'FE001',
  'TK003',
  'BX011',
  'BX024',
  'WG006',
  'BX027',
  'FE014',
  'BX016',
  'WL021',
  'TT013',
  'JU003',
  'WF002',
  'BX003',
  'TK008',
  'BX002',
  'TT012',
  'BX026',
  'TT028',
  'WL003',
  'WL018',
  'FE007',
  'FE002',
  'FE012',
  'BX008',
  'TK002',
  'TT020',
  'JU006',
  'TT031',
  'TT022',
  'WL011',
  'BX018',
  'TT011',
  'JU005',
  'JU012',
  'WF010',
  'WL002',
  'TT032',
  'FE006',
  'FE011',
  'WF001',
  'WF006',
  'JU007',
  'TT026',
  'BX009',
  'TT018',
  'WL017',
  'TK005',
  'TT019',
  'BX013',
  'TT002',
  'JU011',
  'WG005',
  'TK012',
  'TT008',
  'BX028',
  'BX022',
  'WL005',
  'WL012',
  'TT006',
  'TT027',
  'TT017',
  'BX015',
  'BX020',
  'BX007',
  'WG001',
  'JU013',
  'TK009',
  'FE016',
  'FE017',
  'BX017',
  'WF004',
  'BX010',
  'WL006',
  'WF007',
  'WL008',
  'TT009',
  'WL023',
  'TT003',
  'TT023',
  'FE003',
  'BX006',
  'BX025',
  'JU014',
  'FE005',
  'FE015',
  'TK011',
  'TT024',
  'JU002',
  'TT007',
  'BX014',
  'WL007',
  'WF005',
  'JU009',
  'AR011',
  'AR016',
  'AR007',
  'AR008',
  'AR013',
  'AR010',
  '\x96',
  'AR003',
  'AR009',
  'AR015',
  'AR014',
  'AR006',
  'AR005',
  'AR004',
  'AR012',
  'SH002',
  'SH012',
  'SH007',
  'SH009',
  'SH010',
  'SH004',
  'SH014',
  'SH001',
  'FB038',
  'FB015',
  'FB036',
  'FB042',
  'FB026',
  'FB020',
  'FB032',
  'FB040',
  'BK040',
  'BK033',
  'GT001',
  'GA010',
  'GA002',
  'GA001',
  'GA007',
  'BK042',
  'GA012',
  'GA006',
  'BK035',
  'BK038',
  'BK039',
  'GA003',
  'BK036',
  'BK034',
  'GT002',
  'GA005',
  'GA008',
  'BK037',
  'BK041',
  'GA009',
  'GA004',
  'GA011',
  'GA013']}

In [114]:
category_to_sessions['Handball']

['HB001',
 'HB018',
 'HB019',
 'HB006',
 'HB002',
 'HB027',
 'HB024',
 'HB026',
 'HB013',
 'HB005',
 'HB033',
 'HB012',
 'HB034',
 'HB028',
 'HB025',
 'HB010',
 'HB008',
 'HB004',
 'HB003',
 'HB009',
 'HB020',
 'HB015',
 'HB021',
 'HB032',
 'HB011',
 'HB022',
 'HB023',
 'HB029',
 'HB030',
 'HB017',
 'HB016',
 'HB007',
 'HB014',
 'HB031']

In [115]:
sold_tickets['session'].unique()

array(['AT001', 'AT002', 'AT003', 'AT004', 'AT005', 'AT006', 'AT007',
       'AT008', 'AT009', 'AT010', 'AT011', 'AT012', 'AT013', 'AT014',
       'AT015', 'PAT01', 'PAT02', 'PAT03', 'PAT04', 'PAT05', 'PAT06',
       'PAT07', 'PAT08', 'PAT09', 'PAT10', 'PAT11', 'PAT12', 'PAT13',
       'PAT14', 'PAT15', 'PAT16', 'PAT17', 'PAT18', 'SW001', 'SW002',
       'SW003', 'SW004', 'SW005', 'SW006', 'SW007', 'SW008', 'SW009',
       'SW010', 'SW011', 'SW012', 'SW013', 'SW014', 'SW015', 'DV001',
       'DV002', 'DV003', 'DV004', 'DV005', 'DV006', 'DV007', 'DV008',
       'DV009', 'DV010', 'DV011', 'DV012', 'DV013', 'DV014', 'DV015',
       'DV016', 'SY001', 'SY002', 'SY003', 'SY004', 'SY005', 'HO001',
       'HO002', 'HO003', 'HO004', 'HO005', 'HO006', 'HO007', 'HO008',
       'HO009', 'HO010', 'HO011', 'HO012', 'HO013', 'HO014', 'HO015',
       'HO016', 'HO017', 'HO018', 'HO019', 'HO020', 'HO021', 'HO022',
       'HO023', 'HO024', 'HO025', 'HO026', 'HO027', 'HO028', 'HO029',
       'HO030', 'HO031', 'HO032', 'HO033', 'HO034', 'HO035', 'HO036',
       'HO037', 'HO038', 'HO039', 'HO040', 'HO041', 'HO042', 'ED001',
       'ED002', 'ED003', 'ED004', 'EV001', 'EV002', 'EV003', 'EV004',
       'EJ001', 'EJ002', 'EJ003', 'EJ004', 'GA001', 'GA002', 'GA003',
       'GA004', 'GA005', 'GA006', 'GA007', 'GA008', 'GA009', 'GA010',
       'GA011', 'GA012', 'GA013', 'GR001', 'GR002', 'GR003', 'GR004',
       'GT001', 'GT002', 'BX001', 'BX002', 'BX003', 'BX004', 'BX005',
       'BX006', 'BX007', 'BX008', 'BX009', 'BX010', 'BX011', 'BX012',
       'BX013', 'BX014', 'BX015', 'BX016', 'BX017', 'BX018', 'BX019',
       'BX020', 'BX021', 'BX022', 'BX023', 'BX024', 'BX025', 'BX026',
       'BX027', 'BX028', 'TR001', 'TR002', 'CT001', 'CT002', 'CT003',
       'CT004', 'CT005', 'CT006', 'CT007', 'CT008', 'CT009', 'CR001',
       'CR002', 'CR003', 'CR004', 'CR005', 'CR006', 'CR007', 'CR008'],
      dtype=object)

In [111]:
(sold_tickets['session'].isin(category_to_sessions['Handball']) == False).all()

True

In [98]:
sold_tickets['price'].value_counts()
not_special_tickets = sold_tickets.loc[sold_tickets['price'] != 'Special']
not_special_tickets

    session price  number_sold  total_public_sold  percent_sold_to_public
0     AT001   150        16704            46425.0               73.155166
1     AT001    95         7193            46425.0               73.155166
2     AT001    65         6721            46425.0               73.155166
3     AT001    40         4434            46425.0               73.155166
4     AT001    20         5336            46425.0               73.155166
..      ...   ...          ...                ...                     ...
928   CR004    15         5667             6765.0               97.254169
930   CR005    10         5102             6114.0              100.000000
932   CR006    15         5384             6896.0               99.365994
934   CR007    10         4758             6108.0              100.000000
936   CR008    10         1056             1298.0               99.387443

[816 rows x 5 columns]

In [100]:
# session to total money made from tickets 
session_to_earnings = {}
for s in session_codes: 
    s_tickets = not_special_tickets.loc[not_special_tickets['session'] == s]
    total = 0
    for i,ticket in s_tickets.iterrows():
        total = total + (ticket['number_sold'] * float(ticket['price']))
    session_to_earnings[s] = total
session_to_earnings

[key, value ]

{'FE018': 0,
 'FB030': 0,
 'HO010': 360940.0,
 'HB018': 0,
 'VO017': 0,
 'BV033': 0,
 'VO030': 0,
 'TE022': 0,
 'GA002': 680045.0,
 'TT016': 0,
 'VO024': 0,
 'HB013': 0,
 'HO025': 334065.0,
 'AR009': 0,
 'AR016': 0,
 'HO027': 372385.0,
 'TT015': 0,
 'HO019': 320730.0,
 'CT004': 376135.0,
 'TR001': 36120.0,
 'TT030': 0,
 'BK018': 0,
 'DV005': 561900.0,
 'BV031': 0,
 'GA008': 1301245.0,
 'SM002': 0,
 'WP032': 0,
 'DV012': 638345.0,
 'FE004': 0,
 'WL019': 0,
 'GA011': 1343460.0,
 'FB036': 0,
 'BK006': 0,
 'TT004': 0,
 'HB024': 0,
 'HO018': 399170.0,
 'WL010': 0,
 'TE020': 0,
 'WP016': 0,
 'WG006': 0,
 'HB040': 0,
 'VO018': 0,
 'BK002': 0,
 'HB038': 0,
 'WP002': 0,
 'BK025': 0,
 'HO040': 443720.0,
 'WP025': 0,
 'SH002': 0,
 'BV030': 0,
 'SH007': 0,
 'CT009': 324175.0,
 'FB039': 0,
 'WP004': 0,
 'WL018': 0,
 'RO005': 0,
 'DV014': 514150.0,
 'FE007': 0,
 'AT004': 7189125.0,
 'TK002': 0,
 'JU006': 0,
 'CB003': 0,
 'BX018': 349435.0,
 'SH005': 0,
 'AR008': 0,
 'TT032': 0,
 'SW003': 446505.0,
 'HO033': 630480.0,
 'EV003': 1787335.0,
 'BV002': 0,
 'HO035': 547920.0,
 'WF001': 0,
 'FB021': 0,
 'VO013': 0,
 'SY002': 400030.0,
 'FB017': 0,
 'TT002': 0,
 'TE008': 0,
 'AR013': 0,
 'HB041': 0,
 'CS003': 0,
 'BV008': 0,
 'SA002': 0,
 'SA006': 0,
 'SY005': 661195.0,
 'TE012': 0,
 'HB016': 0,
 'TE017': 0,
 'SW012': 919255.0,
 'BV004': 0,
 'BV005': 0,
 'HO002': 483200.0,
 'EJ004': 1831830.0,
 'VO001': 0,
 'ED002': 799660.0,
 'BK004': 0,
 'HB006': 0,
 'BK013': 0,
 'SY001': 360935.0,
 'VO037': 0,
 'DV003': 1255815.0,
 'HB026': 0,
 'BX020': 351670.0,
 'DV013': 1291740.0,
 'BX007': 279995.0,
 'BV009': 0,
 'TK009': 0,
 'HO039': 607845.0,
 'TE013': 0,
 'BK028': 0,
 'WL006': 0,
 'WF007': 0,
 'AT014': 13223675.0,
 'WL008': 0,
 'TT009': 0,
 'WL023': 0,
 'HO037': 403100.0,
 'TT003': 0,
 'DV002': 1103690.0,
 'CT001': 277145.0,
 'BX025': 376495.0,
 'HB011': 0,
 'HB022': 0,
 'DV008': 551040.0,
 'TK011': 0,
 'TT024': 0,
 'HO005': 414905.0,
 'GA004': 657135.0,
 'BV022': 0,
 'SH008': 0,
 'HB007': 0,
 'AT007': 7597580.0,
 'TE007': 0,
 'WL020': 0,
 'AW002': 0,
 'HB042': 0,
 'WP020': 0,
 'HB043': 0,
 'BK026': 0,
 'FB019': 0,
 'BX012': 310630.0,
 'GA001': 542980.0,
 'FB011': 0,
 'WL016': 0,
 'BV001': 0,
 'SW007': 525620.0,
 'WP005': 0,
 'FB029': 0,
 'JU001': 0,
 'FB028': 0,
 'HB028': 0,
 'CB002': 0,
 'TE002': 0,
 'TE021': 0,
 'WP001': 0,
 'FB014': 0,
 'DV015': 561880.0,
 'BV032': 0,
 'SH015': 0,
 'WP021': 0,
 'WF009': 0,
 'FB008': 0,
 'SA005': 0,
 'EJ001': 670490.0,
 'SM001': 0,
 'AT001': 3909880.0,
 'VO021': 0,
 'HO020': 475200.0,
 'CF004': 0,
 'HB014': 0,
 'WP030': 0,
 'WP015': 0,
 'RO002': 0,
 'FB015': 0,
 'HB019': 0,
 'FB013': 0,
 'TE010': 0,
 'VO029': 0,
 'BX005': 284730.0,
 'TT005': 0,
 'TK004': 0,
 'TT014': 0,
 'WP010': 0,
 'BX001': 278840.0,
 'HO006': 359170.0,
 'BX023': 323005.0,
 'FE013': 0,
 'HO004': 399615.0,
 'BK024': 0,
 'SH011': 0,
 'ED003': 1149265.0,
 'BK029': 0,
 'AT003': 3289210.0,
 'BK030': 0,
 'SW005': 480325.0,
 'HO009': 349205.0,
 'FE014': 0,
 'BX016': 321675.0,
 'WL021': 0,
 'DV004': 748315.0,
 'EV004': 1071130.0,
 'SA013': 0,
 'VO012': 0,
 'AR004': 0,
 'BK017': 0,
 'SH014': 0,
 'TE019': 0,
 'SA007': 0,
 'HO016': 382680.0,
 'BX026': 394065.0,
 'VO036': 0,
 'AT013': 6608590.0,
 'BK037': 0,
 'FB007': 0,
 'FB034': 0,
 'BV026': 0,
 'SW009': 454545.0,
 'CT003': 129465.0,
 'TE009': 0,
 'WP026': 0,
 'AT002': 8887170.0,
 'BV016': 0,
 'VO020': 0,
 'HO026': 494810.0,
 'BD022': 0,
 'HB002': 0,
 'FB037': 0,
 'BV021': 0,
 'VO034': 0,
 'WP028': 0,
 'HB046': 0,
 'TE004': 0,
 'SH012': 0,
 'BD010': 0,
 'FB006': 0,
 'CM002': 0,
 'RO003': 0,
 'SW010': 784665.0,
 'HO042': 524750.0,
 'VO011': 0,
 'HO031': 346240.0,
 'FB038': 0,
 'WF006': 0,
 'TT026': 0,
 'FB041': 0,
 'CR002': 65480.0,
 'BK034': 0,
 'BD019': 0,
 'TE015': 0,
 'VO039': 0,
 'HO003': 374010.0,
 'BD018': 0,
 'WG005': 0,
 'BK031': 0,
 'AR003': 0,
 'SH013': 0,
 'CS004': 0,
 'TT008': 0,
 'BX028': 870985.0,
 'DV006': 764960.0,
 'BD005': 0,
 'WP029': 0,
 'CT006': 349565.0,
 'VO015': 0,
 'WL012': 0,
 'VO003': 0,
 'HB035': 0,
 'FB033': 0,
 'HB036': 0,
 'GR001': 119715.0,
 'BX015': 308665.0,
 'WP027': 0,
 'JU013': 0,
 'BK022': 0,
 'FE016': 0,
 'WF004': 0,
 'BK042': 0,
 'BK011': 0,
 'BV007': 0,
 'BK032': 0,
 'VO040': 0,
 'BK035': 0,
 'BK009': 0,
 'BK020': 0,
 'WP008': 0,
 'SW015': 858225.0,
 'HB003': 0,
 'BD023': 0,
 'TT023': 0,
 'BK005': 0,
 'FB026': 0,
 'BX006': 230735.0,
 'BD011': 0,
 'HB032': 0,
 'EJ003': 1106285.0,
 'BD017': 0,
 'SW008': 897430.0,
 'FE005': 0,
 'BV020': 0,
 'SH006': 0,
 'BX014': 315775.0,
 'WL004': 0,
 'WL007': 0,
 'BD002': 0,
 'MP003': 0,
 'HO011': 461255.0,
 'BK040': 0,
 'FB016': 0,
 'FB001': 0,
 'SW006': 908600.0,
 'BK033': 0,
 'FE009': 0,
 'TT010': 0,
 'BX021': 319580.0,
 'HB027': 0,
 'VO008': 0,
 'FE008': 0,
 'WP022': 0,
 'MP001': 0,
 'TK006': 0,
 'WP007': 0,
 'WL014': 0,
 'WL015': 0,
 'AT012': 3874080.0,
 'CF002': 0,
 'ED001': 757935.0,
 'HO023': 417170.0,
 'HB012': 0,
 'VO005': 0,
 'BX019': 372840.0,
 'VO019': 0,
 'DV001': 707205.0,
 'FB027': 0,
 'VO026': 0,
 'CS005': 0,
 'BD021': 0,
 'SH009': 0,
 'WG003': 0,
 'VO042': 0,
 'HB009': 0,
 'BK036': 0,
 'BD014': 0,
 'FB004': 0,
 'RO001': 0,
 'SW002': 673185.0,
 'JU008': 0,
 'JU004': 0,
 'BD004': 0,
 'AT006': 3311550.0,
 'AM002': 0,
 'VO010': 0,
 'WF003': 0,
 'TE006': 0,
 'JU010': 0,
 'CF005': 0,
 'VO023': 0,
 'HO034': 416745.0,
 'AR007': 0,
 'FB005': 0,
 'SA011': 0,
 'TK010': 0,
 'TT021': 0,
 'HO030': 409135.0,
 'VO002': 0,
 'WL009': 0,
 'WL001': 0,
 'WL013': 0,
 'SA004': 0,
 'WP033': 0,
 'WG004': 0,
 'BV018': 0,
 'VO033': 0,
 'GA012': 1463145.0,
 'BV012': 0,
 'CT005': 121675.0,
 'RO007': 0,
 'TE023': 0,
 'BX024': 853315.0,
 'TE016': 0,
 'BX027': 869675.0,
 'WP017': 0,
 'HO038': 735370.0,
 'BD003': 0,
 'FB012': 0,
 'DV010': 796010.0,
 'TT013': 0,
 'HB021': 0,
 'JU003': 0,
 'FB003': 0,
 'BX003': 282690.0,
 'FB024': 0,
 'TT012': 0,
 'VO035': 0,
 'VO006': 0,
 'WL003': 0,
 'SW001': 349860.0,
 'BV017': 0,
 'BV028': 0,
 'TE003': 0,
 'SA012': 0,
 'HB044': 0,
 'HB031': 0,
 'HB045': 0,
 'RO008': 0,
 'FE002': 0,
 'FB010': 0,
 'FE012': 0,
 'BX008': 310915.0,
 'TT020': 0,
 'FB018': 0,
 'TT031': 0,
 'TT022': 0,
 'HO028': 371890.0,
 'TT011': 0,
 'FB022': 0,
 'WF010': 0,
 'WP009': 0,
 'HB005': 0,
 'TE024': 0,
 'HB034': 0,
 'FE006': 0,
 'DV016': 1011545.0,
 'BD007': 0,
 'SH001': 0,
 'FE011': 0,
 'VO031': 0,
 'DV011': 604920.0,
 'BD008': 0,
 'HB025': 0,
 'VO022': 0,
 'BK039': 0,
 'CF003': 0,
 'TR002': 29760.0,
 'ED004': 2138745.0,
 'GR004': 266420.0,
 'BK012': 0,
 'AT005': 9895585.0,
 'WL017': 0,
 'AT009': 8077235.0,
 'JU011': 0,
 'SH010': 0,
 'HO001': 292345.0,
 'HO015': 393460.0,
 'WP003': 0,
 'WL005': 0,
 'CS002': 0,
 'FB032': 0,
 'AT015': 12550605.0,
 'AM001': 0,
 'BD020': 0,
 'HO022': 419925.0,
 'FB031': 0,
 'TT017': 0,
 'AT010': 3679715.0,
 'WP023': 0,
 'AW003': 0,
 'BV034': 0,
 'WG001': 0,
 'VO016': 0,
 'HB039': 0,
 'HB033': 0,
 'BV015': 0,
 'CR001': 61100.0,
 'FE017': 0,
 'SA003': 0,
 'SW014': 985135.0,
 'BX010': 325060.0,
 'BD009': 0,
 'BD016': 0,
 'BD001': 0,
 'HB010': 0,
 'BK016': 0,
 'MP002': 0,
 'VO009': 0,
 'WP014': 0,
 'GR003': 242265.0,
 'RO006': 0,
 'FB002': 0,
 'JU014': 0,
 'BK007': 0,
 'FE015': 0,
 'CS001': 0,
 'HB017': 0,
 'JU002': 0,
 'BK003': 0,
 'BV003': 0,
 'GT002': 955180.0,
 'BK021': 0,
 'TT001': 0,
 'SA009': 0,
 'AR005': 0,
 'TK007': 0,
 'HO008': 465455.0,
 'GA007': 1505325.0,
 'HO032': 546060.0,
 'BD013': 0,
 'TT025': 0,
 'BD006': 0,
 'HB037': 0,
 'HB008': 0,
 'GA003': 617910.0,
 'WP024': 0,
 'CT008': 127630.0,
 'FB020': 0,
 'HO029': 552805.0,
 'BX004': 245425.0,
 'HO013': 333310.0,
 'WL022': 0,
 'GA013': 1247955.0,
 'AR012': 0,
 'BD012': 0,
 'WF008': 0,
 'WG002': 0,
 'HB001': 0,
 'BK015': 0,
 'TK001': 0,
 'WP006': 0,
 'FB042': 0,
 'TT029': 0,
 'VO028': 0,
 'WP018': 0,
 'EJ002': 666845.0,
 'VO004': 0,
 'RO004': 0,
 'VO007': 0,
 'BV027': 0,
 'HO021': 281470.0,
 'FE010': 0,
 'CF001': 0,
 'AR010': 0,
 'FB009': 0,
 'FE001': 0,
 'BK027': 0,
 'AR014': 0,
 'FB025': 0,
 'HO036': 455625.0,
 'TK003': 0,
 'GA006': 693720.0,
 'SY004': 405915.0,
 'WP011': 0,
 'BV019': 0,
 'BX011': 312765.0,
 'SA010': 0,
 'WP019': 0,
 'SY003': 704245.0,
 'SH004': 0,
 'AW001': 0,
 'WF002': 0,
 'GA005': 724610.0,
 'CB001': 0,
 'TK008': 0,
 'BX002': 279850.0,
 'HB023': 0,
 'HO014': 445185.0,
 'VO027': 0,
 'TT028': 0,
 'BV011': 0,
 'WP012': 0,
 'BV014': 0,
 'GA009': 1511850.0,
 'CM001': 0,
 'AR006': 0,
 'AT008': 3965070.0,
 'SA008': 0,
 'CT002': 307200.0,
 'HO041': 664680.0,
 'WL011': 0,
 'BV010': 0,
 'SW011': 482815.0,
 'JU005': 0,
 'JU012': 0,
 'BV006': 0,
 'BV025': 0,
 'BK010': 0,
 'BV013': 0,
 'VO032': 0,
 'WL002': 0,
 'BD024': 0,
 'HO024': 374040.0,
 'EV001': 621325.0,
 'TE011': 0,
 'SW013': 559285.0,
 'BV029': 0,
 'SA001': 0,
 'WP031': 0,
 'TE014': 0,
 'TE018': 0,
 'WP013': 0,
 'JU007': 0,
 'HB004': 0,
 'TE005': 0,
 'AR015': 0,
 'BX009': 314120.0,
 'HO007': 287580.0,
 'TT018': 0,
 'CT007': 266355.0,
 'GR002': 129410.0,
 'AT011': 8030955.0,
 'TK005': 0,
 'AR011': 0,
 'TT019': 0,
 'BX013': 292375.0,
 'EV002': 662905.0,
 'HB029': 0,
 'HO012': 371855.0,
 'HB030': 0,
 'MP004': 0,
 'BK041': 0,
 'TK012': 0,
 'BX022': 346860.0,
 'FB040': 0,
 'SH003': 0,
 'VO014': 0,
 'VO025': 0,
 '\x96': 0,
 'GT001': 938505.0,
 'TT006': 0,
 'GA010': 909580.0,
 'TT027': 0,
 'BV024': 0,
 'FB023': 0,
 'SA014': 0,
 'FB035': 0,
 'BK008': 0,
 'BX017': 266695.0,
 'BK014': 0,
 'HO017': 435110.0,
 'BK019': 0,
 'CF006': 0,
 'BK038': 0,
 'TE001': 0,
 'FE003': 0,
 'HB020': 0,
 'HB015': 0,
 'BV023': 0,
 'BK001': 0,
 'DV007': 790595.0,
 'BD015': 0,
 'SW004': 734355.0,
 'VO038': 0,
 'VO041': 0,
 'DV009': 726115.0,
 'TT007': 0,
 'BK023': 0,
 'WF005': 0,
 'JU009': 0}

In [104]:
category_to_earnings = {}
for c in categories: 
    if c == 'Total Venues': # skip
        continue
    c_sessions = category_to_sessions[c]
    earnings = 0
    for s in c_sessions: 
        earnings = earnings + session_to_earnings[s]
    category_to_earnings[c] = earnings

category_to_earnings

{'Stadium': 104090025.0,
 'Aquatics': 25220350.0,
 'Velopark': 2279345.0,
 'Handball': 0,
 'Basketball': 0,
 'Other Olympic Park Venues': 18154610.0,
 'Non-Olympic Park Venues': 39695530.0}